### PR TITLE
Confiuge ci sonar cloud

### PR DESCRIPTION
**Pull request by amrsamii**
I used GitHub actions for CI

### CODE REVIEW

**Comment by nfrankel** [comment]
Why is the report empty?

https://sonarcloud.io/dashboard?id=amrsamii_hazelcast-kotlindsl

**Comment by amrsamii** [comment]
This report was made automatically by SonarCloud when I integrated with the Repo, the code coverage was not configured yet, but the report analyzed 266 lines of kotlin and 67 lines of xml and it did not find any problem. Now the automatic analysis is turned off and it will be triggered only when a successful build is made, then code coverage will appear.

**Comment by nfrankel** [comment]
Build fails.

I've created [an issue](https://github.com/nfrankel/hazelcast-kotlindsl/issues/5)

**Comment by amrsamii** [comment]
I am working on it

**Pull request merged**
