### PR TITLE
Add some MapConfigDsl tests

### PR DESCRIPTION
**Pull request by amrsamii**

### CODE REVIEW

**Comment by amrsamii** [comment]
since the PR is considered external to SonarCloud project, it will not be analyzed, hence, the build fails

**Comment by nfrankel** [comment]
I've configured the project on SonarCloud (and removed the sonar:sonar target from the action), please rebase this branch on master and push force the branch to update the PR.

**Comment by amrsamii** [comment]
I think you need to turn off automatic analysis of SonarCloud in order to trigger it only by GitHub action

**Comment by nfrankel** [comment]
Next steps:

* Make Sonar get the test coverage :-)
* Configure Sonar rules because obviously, I like my test methods to have long names

**Comment by amrsamii** [comment]
Maven command in GitHub action does not have sonar target now, do you want from me to add it now so that after build is successful, SonarCloud analysis is triggered with code coverage?

**Comment by nfrankel** [comment]
I removed the Sonar target from Maven because it didn't work. I had to run a first analysis, so I linked the project.

If you believe that the Sonar target should be re-added, please do so. A couple of things:

* Why `verify`? So far, we are not doing anything with the package anyway. I believe `test` should be enough, unless you have something on your mind
* `clean` is not necessary since it starts from scratch every time
* Is there a way to cache the dependencies from build to build? It's useless to download them every time
* Can you put the coverage in the regular build? I avoid profiles as much as I can, because only the implementer knows which one should be activated in which case

**Comment by amrsamii** [comment]
I think sonar target should be added to the workflow, it will now work after you made a new SonarCloud project that is configured with the main repo.
I will talk about things you mentioned in order:
- actually, `verify` is the phase that generates `jacoco` report, so it is needed to produce the report and then SonarCloud can get the report
- it is really not necessary but now I will add caching so I think it will be necessary, what do you think?
- actually, there is a way, I will make a PR to add caching to workflow
- if it is not added to profiles, it will be added to plugins. both ways will work, but I really don't understand why you avoid profiles.

I will make a PR that adds caching to workflow, then PR that add sonar to workflow. what do you think?

**Pull request merged**
